version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=l2
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - dbdata:/var/lib/mysql

  laravel:
#    image: 'rafaelsantin/laravel:latest'
    build: .
    environment:
      - APP_ENV=development
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_DATABASE=l2
      - DB_PASSWORD=root
    depends_on:
      - db
    links:
      - "db:db"
    ports:
      - 82:80


volumes:
  dbdata:


#docker-compose exec laravel php artisan migrate --force